// 字库版本号：字库有改动就改一下，方便确认电视端用的是哪一版
window.WORDS_VERSION = "2026-09-14";
window.WORING = '版本所有：郭东波';
// 幼儿园学的字
window.words_youeryuan = [
    { "word": "儿", "pinyin": "er", "tip": "👶" },
    { "word": "爸", "pinyin": "ba", "tip": "👨" },
    { "word": "人", "pinyin": "ren", "tip": "🧑" },
    { "word": "口", "pinyin": "kou", "tip": "👄" },
    { "word": "妈", "pinyin": "ma", "tip": "👩" },
    { "word": "西", "pinyin": "xi", "tip": "🧭" },
    { "word": "中", "pinyin": "zhong", "tip": "🎯" },
    { "word": "个", "pinyin": "ge", "tip": "🧩" },
    { "word": "男", "pinyin": "nan", "tip": "👦" },
    { "word": "水", "pinyin": "shui", "tip": "💧" },
    { "word": "土", "pinyin": "tu", "tip": "🌱" },
    { "word": "下", "pinyin": "xia", "tip": "👇" },
    { "word": "三", "pinyin": "san", "tip": "3️⃣" },
    { "word": "十", "pinyin": "shi", "tip": "🔟" },
    { "word": "女", "pinyin": "nv", "tip": "👧" },
    { "word": "皮", "pinyin": "pi", "tip": "🍌" },
    { "word": "工", "pinyin": "gong", "tip": "👷" },
    { "word": "六", "pinyin": "liu", "tip": "6️⃣" },
    { "word": "左", "pinyin": "zuo", "tip": "👈" },
    { "word": "五", "pinyin": "wu", "tip": "5️⃣" },
    { "word": "九", "pinyin": "jiu", "tip": "9️⃣" },
    { "word": "七", "pinyin": "qi", "tip": "7️⃣" },
    { "word": "八", "pinyin": "ba", "tip": "8️⃣" },
    { "word": "四", "pinyin": "si", "tip": "4️⃣" },
]
// 幼儿园常见字体

window.words_youeryuan_common = [
    // 方位
    { "word": "上", "pinyin": "shang", "tip": "⬆️" },
    { "word": "下", "pinyin": "xia", "tip": "👇" },
    { "word": "左", "pinyin": "zuo", "tip": "👈" },
    { "word": "右", "pinyin": "you", "tip": "👉" },
    { "word": "前", "pinyin": "qian", "tip": "⏩" },
    { "word": "后", "pinyin": "hou", "tip": "⏪" },
    { "word": "里", "pinyin": "li", "tip": "📥" },
    { "word": "外", "pinyin": "wai", "tip": "📤" },
    { "word": "中", "pinyin": "zhong", "tip": "🎯" },
    // 大小 / 程度
    { "word": "大", "pinyin": "da", "tip": "🐘" },
    { "word": "小", "pinyin": "xiao", "tip": "🐜" },
    { "word": "多", "pinyin": "duo", "tip": "🍇" },
    { "word": "少", "pinyin": "shao", "tip": "🍒" },
    { "word": "高", "pinyin": "gao", "tip": "🦒" },
    { "word": "长", "pinyin": "chang", "tip": "📏" },
    { "word": "好", "pinyin": "hao", "tip": "👍" },
    // 人 / 身体
    { "word": "人", "pinyin": "ren", "tip": "🧑" },
    { "word": "口", "pinyin": "kou", "tip": "👄" },
    { "word": "手", "pinyin": "shou", "tip": "✋" },
    { "word": "足", "pinyin": "zu", "tip": "🦶" },
    { "word": "目", "pinyin": "mu", "tip": "👁️" },
    { "word": "耳", "pinyin": "er", "tip": "👂" },
    { "word": "心", "pinyin": "xin", "tip": "❤️" },
    { "word": "牙", "pinyin": "ya", "tip": "🦷" },
    { "word": "鼻", "pinyin": "bi", "tip": "👃" },
    // 自然
    { "word": "日", "pinyin": "ri", "tip": "☀️" },
    { "word": "月", "pinyin": "yue", "tip": "🌙" },
    { "word": "星", "pinyin": "xing", "tip": "⭐" },
    { "word": "云", "pinyin": "yun", "tip": "☁️" },
    { "word": "雨", "pinyin": "yu", "tip": "🌧️" },
    { "word": "风", "pinyin": "feng", "tip": "🌬️" },
    { "word": "火", "pinyin": "huo", "tip": "🔥" },
    { "word": "山", "pinyin": "shan", "tip": "⛰️" },
    { "word": "石", "pinyin": "shi", "tip": "🪨" },
    { "word": "土", "pinyin": "tu", "tip": "🌱" },
    { "word": "田", "pinyin": "tian", "tip": "🌾" },
    { "word": "木", "pinyin": "mu", "tip": "🪵" },
    { "word": "花", "pinyin": "hua", "tip": "🌸" },
    { "word": "草", "pinyin": "cao", "tip": "🌿" },
    { "word": "树", "pinyin": "shu", "tip": "🌳" },
    { "word": "天", "pinyin": "tian", "tip": "🌤️" },
    { "word": "水", "pinyin": "shui", "tip": "💦" },
    { "word": "地", "pinyin": "di", "tip": "🌏" },
    // 动物
    { "word": "牛", "pinyin": "niu", "tip": "🐮" },
    { "word": "羊", "pinyin": "yang", "tip": "🐑" },
    { "word": "马", "pinyin": "ma", "tip": "🐴" },
    { "word": "鸟", "pinyin": "niao", "tip": "🐦" },
    { "word": "鱼", "pinyin": "yu", "tip": "🐟" },
    { "word": "虫", "pinyin": "chong", "tip": "🐛" },
    { "word": "猫", "pinyin": "mao", "tip": "🐱" },
    { "word": "狗", "pinyin": "gou", "tip": "🐶" },
    { "word": "兔", "pinyin": "tu", "tip": "🐰" },
    // 家人
    { "word": "爸", "pinyin": "ba", "tip": "👨" },
    { "word": "妈", "pinyin": "ma", "tip": "👩" },
    { "word": "爷", "pinyin": "ye", "tip": "👴" },
    { "word": "奶", "pinyin": "nai", "tip": "👵" },
    { "word": "儿", "pinyin": "er", "tip": "👶" },
    // 男 / 女
    { "word": "男", "pinyin": "nan", "tip": "👦" },
    { "word": "女", "pinyin": "nv", "tip": "👧" },
    // 物品 / 动作
    { "word": "车", "pinyin": "che", "tip": "🚗" },
    { "word": "门", "pinyin": "men", "tip": "🚪" },
    { "word": "书", "pinyin": "shu", "tip": "📖" },
    { "word": "笔", "pinyin": "bi", "tip": "🖊️" },
    { "word": "走", "pinyin": "zou", "tip": "🚶" },
    { "word": "看", "pinyin": "kan", "tip": "👀" },
    { "word": "说", "pinyin": "shuo", "tip": "🗣️" },
    { "word": "吃", "pinyin": "chi", "tip": "🍽️" },
    { "word": "喝", "pinyin": "he", "tip": "🥛" },
    { "word": "笑", "pinyin": "xiao", "tip": "😄" },
    // 其他常用
    { "word": "个", "pinyin": "ge", "tip": "🧩" },
    { "word": "工", "pinyin": "gong", "tip": "👷" },
    { "word": "皮", "pinyin": "pi", "tip": "🍌" },
    { "word": "西", "pinyin": "xi", "tip": "🧭" },
    // 数字
    { "word": "一", "pinyin": "yi", "tip": "1️⃣" },
    { "word": "二", "pinyin": "er", "tip": "2️⃣" },
    { "word": "三", "pinyin": "san", "tip": "3️⃣" },
    { "word": "四", "pinyin": "si", "tip": "4️⃣" },
    { "word": "五", "pinyin": "wu", "tip": "5️⃣" },
    { "word": "六", "pinyin": "liu", "tip": "6️⃣" },
    { "word": "七", "pinyin": "qi", "tip": "7️⃣" },
    { "word": "八", "pinyin": "ba", "tip": "8️⃣" },
    { "word": "九", "pinyin": "jiu", "tip": "9️⃣" },
    { "word": "十", "pinyin": "shi", "tip": "🔟" },
]
